# .eslintrc.yml

env:
  node: true

extends:
  - "airbnb-base"

plugins:
  - "import"

rules:
  # Отключение правила no-console
  no-console: "off"

  # Отключение правила import/extensions
  import/extensions: "off"

# Добавьте дополнительные правила, если необходимо

